# Generated by Django 3.0.2 on 2020-01-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('student_ID', models.IntegerField(default=0)),
                ('email_address', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
