# Generated by Django 3.0.2 on 2020-01-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services_app', '0001_initial'),
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Total', models.IntegerField(default=0)),
                ('Discount', models.IntegerField(default=0)),
                ('Total_Amount', models.IntegerField(default=0)),
                ('Total_Paid', models.IntegerField(default=0)),
                ('Due', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=25)),
                ('PatientName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='patient_app.Patient')),
                ('ServiceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_app.Service')),
            ],
        ),
    ]
