# Generated by Django 3.0.2 on 2020-01-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.CharField(max_length=512)),
                ('gender', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField()),
                ('is_visited', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='doctor_app.Doctor')),
            ],
        ),
    ]
