# Generated by Django 3.0.2 on 2020-02-07 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_visited',
        ),
        migrations.AddField(
            model_name='patient',
            name='advice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='complain',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='dose',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='observation',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 19, 36, 27, 248553)),
        ),
        migrations.AddField(
            model_name='patient',
            name='MedNAme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient_app.Medicine'),
        ),
    ]
