# Generated by Django 3.0.2 on 2020-02-07 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_auto_20200207_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='MedNAme',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 1, 34, 6, 234268)),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
