# Generated by Django 3.0.2 on 2020-02-08 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0006_auto_20200208_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 13, 55, 11, 727291)),
        ),
    ]
