# Generated by Django 3.0.2 on 2020-02-08 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0007_auto_20200208_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 14, 1, 46, 218357)),
        ),
    ]
