# Generated by Django 3.0.2 on 2020-03-16 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0011_auto_20200316_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 20, 27, 30, 455728)),
        ),
    ]
