# Generated by Django 3.0.2 on 2020-01-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='dose',
            field=models.CharField(max_length=20),
        ),
    ]
