# Generated by Django 3.0.2 on 2020-01-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient_app', '0002_auto_20200119_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpatient',
            name='MedNAme',
        ),
        migrations.AddField(
            model_name='addpatient',
            name='MedNAme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='addpatient_app.Medicine'),
        ),
    ]
