# Generated by Django 3.0.2 on 2020-01-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient_app', '0005_auto_20200119_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpatient',
            old_name='Name',
            new_name='PatientName',
        ),
    ]
