# Generated by Django 3.0.2 on 2020-01-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient_app', '0007_auto_20200119_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddPatient',
        ),
    ]
