# Generated by Django 3.0.2 on 2020-01-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
        ('addpatient_app', '0008_delete_addpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField(max_length=250)),
                ('observation', models.TextField(max_length=250)),
                ('advice', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('diabetes', models.BooleanField()),
                ('blood_group', models.CharField(max_length=15)),
                ('MedNAme', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='addpatient_app.Medicine')),
                ('PatientName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addpatient', to='patient_app.Patient')),
            ],
        ),
    ]
