# Generated by Django 3.0.2 on 2020-01-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
        ('addpatient_app', '0010_auto_20200119_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpatient',
            name='MedNAme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='addpatient_app.Medicine'),
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='PatientName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addpatient', to='patient_app.Patient'),
        ),
    ]
