# Generated by Django 3.0.2 on 2020-02-07 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
        ('addpatient_app', '0012_auto_20200119_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='MedNAme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='addpatient_app.Medicine'),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='PatientName',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addpatient', to='patient_app.Patient'),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='advice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='blood_group',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='complain',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 18, 45, 36, 330143)),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='dose',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='observation',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
