# Generated by Django 3.0.2 on 2020-02-07 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_app', '0001_initial'),
        ('addpatient_app', '0014_auto_20200207_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AddPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField(default='', max_length=250)),
                ('observation', models.TextField(default='', max_length=250)),
                ('advice', models.CharField(default='', max_length=200)),
                ('dose', models.CharField(default='', max_length=20)),
                ('duration', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 18, 55, 48, 736976))),
                ('diabetes', models.BooleanField(default=False)),
                ('blood_group', models.CharField(default='', max_length=15)),
                ('MedNAme', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='addpatient_app.Medicine')),
                ('PatientName', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addpatient', to='patient_app.Patient')),
            ],
        ),
    ]
