# Generated by Django 3.0.2 on 2020-02-07 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient_app', '0015_addpatient_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpatient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 19, 3, 40, 485328)),
        ),
    ]
