# Generated by Django 3.0.2 on 2020-02-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient_app', '0016_auto_20200207_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddPatient',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
