# Generated by Django 3.0.2 on 2020-03-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('no', models.IntegerField(default=0)),
                ('ltd', models.CharField(default='', max_length=255)),
                ('msg', models.TextField(default='', max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='docavailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='', max_length=255)),
                ('day', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
