# Generated by Django 3.0.2 on 2020-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0003_appointment_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visited',
            field=models.CharField(default='False', max_length=255),
        ),
    ]
