# Generated by Django 3.0.2 on 2020-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0004_auto_20200318_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visited',
            field=models.CharField(default='No', max_length=255),
        ),
    ]
