# Generated by Django 3.0.2 on 2020-02-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicine',
        ),
    ]
